### ISSUE TITLE
IF_Chat_Avatar.json Workflow / VHS_VideoCombine Node

### ISSUE THREAD

**Issue by androideve** [if-ai/ComfyUI-IF_AI_WishperSpeechNode#2]
Thank you so much for your nodes! Really appreciate the work you put into this and sharing it with everyone.

I'm using the IF_Chat_Avatar workflow that is included, but every time the workflow gets to the Video Combine node, it freezes and won't complete the workflow. 

In terminal for comfyui, it hangs after this:

```
Moviepy - Building video D:\ai\ComfyUI_windows_portable\ComfyUI\output\IF_AI_DreamTalk_20240429125027\IF_AI_DreamTalk_20240429125027_converted.mp4.
MoviePy - Writing audio in IF_AI_DreamTalk_20240429125027_convertedTEMP_MPY_wvf_snd.mp4
MoviePy - Done.
Moviepy - Writing video D:\ai\ComfyUI_windows_portable\ComfyUI\output\IF_AI_DreamTalk_20240429125027\IF_AI_DreamTalk_20240429125027_converted.mp4

Moviepy - Done !
Moviepy - video ready D:\ai\ComfyUI_windows_portable\ComfyUI\output\IF_AI_DreamTalk_20240429125027\IF_AI_DreamTalk_20240429125027_converted.mp4
```

The file IF_AI_DreamTalk_20240429125027\IF_AI_DreamTalk_20240429125027_converted.mp4 plays just fine, but I'm wondering what the final Video Combine nodes does in the workflow and if it's necessary.

I've tested out VHS_VideoCombine node in other workflows and it works without issue.

Thanks again

**Comment by if-ai** [comment]
if it finish the dreamtalk node the video would be on the output folder. The VHS is just to display in comfy I am attempting to code a new video node the VHS des a lot of unnecessary computation to just display the video. sorry I didn't answer before somehow I missed this message
