### ISSUE TITLE
not found: IF_DreamTalk  Nodes that have failed to load will show as red on the graph.

### ISSUE THREAD

**Issue by zayedh25** [if-ai/ComfyUI-IF_AI_WishperSpeechNode#4]
Thanks but I faced this problem the node is missing  ((   When loading the graph, the following node types were not found:
IF_DreamTalk 
Nodes that have failed to load will show as red on the graph.

**Comment by if-ai** [comment]
Hi, the nodes are https://github.com/if-ai/ComfyUI-IF_AI_Dreamtalk you have to recreate the nodes or just load them from the impactframes node menu

**Comment by zayedh25** [comment]
Thanks bro
