### ISSUE TITLE
Not an issue, just a thanks!

### ISSUE THREAD

**Issue by GeekyGhost** [if-ai/ComfyUI-IF_AI_WishperSpeechNode#5]
So this was super simple. load a .ogg audio file with clean speech of around 10 minutes with a diverse script and you seem to be good to go. Awesome work!

**Comment by if-ai** [comment]
Thank you, glad you like it. I have some new feature ideas that I want to add after I add memory and rag to the IF_AI_tools I will work to them as soon as I can. I think comfy users will enjoy them.

**Comment by GeekyGhost** [comment]
> Thank you, glad you like it. I have some new feature ideas that I want to add after I add memory and rag to the IF_AI_tools I will work to them as soon as I can. I think comfy users will enjoy them.

I've made an AI assistant in comfyUI with your nodes lol. https://civitai.com/models/465631/geeky-ghost-ai-voice-assistant-workflow

**Comment by if-ai** [comment]
That's awesome thank you <3

**Comment by GeekyGhost** [comment]
> That's awesome thank you <3

Now I'm feeding IF AI into IF Whisper and then into Wav2Lip to make voiced videos LOL!
