### ISSUE TITLE
torch_compile error

### ISSUE THREAD

**Issue by PrometheusDante** [if-ai/ComfyUI-IF_AI_WishperSpeechNode#6]
Hello, 
when trying to activate `torch_compile` on the whisper speech node to speed up the process, but got the following error:

<details>
  <summary>Error 1</summary>

> Error occurred when executing IF_WhisperSpeech:
> 
> backend='inductor' raised:
> RuntimeError: Cannot find a working triton installation. More information on installing Triton can be found at https://github.com/openai/triton
> 
> Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
> 
> 
> You can suppress this exception and fall back to eager by setting:
>     import torch._dynamo
>     torch._dynamo.config.suppress_errors = True
> 
> 
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_WishperSpeechNode\IFWhisperSpeechNode.py", line 114, in generate_audio
>     stoks = pipe.t2s.generate(chunk, cps=cps, show_progress_bar=False)[0]
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\whisperspeech\t2s_up_wds_mlang_enclm.py", line 462, in generate
>     toks[:,i+1] = self.generate_next(toks[:,i:i+1], toks_positions[i:i+1], cps_emb, xenc, xenc_positions, T, top_k)[:,0]
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\eval_frame.py", line 451, in _fn
>     return fn(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 921, in catch_errors
>     return callback(frame, cache_entry, hooks, frame_state, skip=1)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 400, in _convert_frame_assert
>     return _compile(
>   File "contextlib.py", line 79, in inner
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 676, in _compile
>     guarded_code = compile_inner(code, one_graph, hooks, transform)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 535, in compile_inner
>     out_code = transform_code_object(code, transform)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1036, in transform_code_object
>     transformations(instructions, code_options)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 165, in _fn
>     return fn(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 500, in transform
>     tracer.run()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2149, in run
>     super().run()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 810, in run
>     and self.step()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 773, in step
>     getattr(self, inst.opname)(inst)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2268, in RETURN_VALUE
>     self.output.compile_subgraph(
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\output_graph.py", line 971, in compile_subgraph
>     self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
>   File "contextlib.py", line 79, in inner
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\output_graph.py", line 1168, in compile_and_call_fx_graph
>     compiled_fn = self.call_user_compiler(gm)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\output_graph.py", line 1241, in call_user_compiler
>     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\output_graph.py", line 1222, in call_user_compiler
>     compiled_fn = compiler_fn(gm, self.example_inputs())
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 117, in debug_wrapper
>     compiled_gm = compiler_fn(gm, example_inputs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 117, in debug_wrapper
>     compiled_gm = compiler_fn(gm, example_inputs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\__init__.py", line 1729, in __call__
>     return compile_fx(model_, inputs_, config_patches=self.config)
>   File "contextlib.py", line 79, in inner
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\compile_fx.py", line 1102, in compile_fx
>     return compile_fx(
>   File "contextlib.py", line 79, in inner
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\compile_fx.py", line 1330, in compile_fx
>     return aot_autograd(
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\backends\common.py", line 58, in compiler_fn
>     cg = aot_module_simplified(gm, example_inputs, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_functorch\aot_autograd.py", line 903, in aot_module_simplified
>     compiled_fn = create_aot_dispatcher_function(
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_functorch\aot_autograd.py", line 628, in create_aot_dispatcher_function
>     compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 443, in aot_wrapper_dedupe
>     return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
>     return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 119, in aot_dispatch_base
>     compiled_fw = compiler(fw_module, updated_flat_args)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\compile_fx.py", line 1257, in fw_compiler_base
>     return inner_compile(
>   File "contextlib.py", line 79, in inner
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\repro\after_aot.py", line 83, in debug_wrapper
>     inner_compiled_fn = compiler_fn(gm, example_inputs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\debug.py", line 304, in inner
>     return fn(*args, **kwargs)
>   File "contextlib.py", line 79, in inner
>   File "contextlib.py", line 79, in inner
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\compile_fx.py", line 438, in compile_fx_inner
>     compiled_graph = fx_codegen_and_compile(
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\compile_fx.py", line 714, in fx_codegen_and_compile
>     compiled_fn = graph.compile_to_fn()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\graph.py", line 1307, in compile_to_fn
>     return self.compile_to_module().call
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\graph.py", line 1250, in compile_to_module
>     self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\graph.py", line 1205, in codegen
>     self.scheduler = Scheduler(self.buffers)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\scheduler.py", line 1267, in __init__
>     self.nodes = [self.create_scheduler_node(n) for n in nodes]
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\scheduler.py", line 1267, in 
>     self.nodes = [self.create_scheduler_node(n) for n in nodes]
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\scheduler.py", line 1358, in create_scheduler_node
>     return SchedulerNode(self, node)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\scheduler.py", line 687, in __init__
>     self._compute_attrs()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\scheduler.py", line 698, in _compute_attrs
>     group_fn = self.scheduler.get_backend(self.node.get_device()).group_fn
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\scheduler.py", line 2276, in get_backend
>     self.backends[device] = self.create_backend(device)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\scheduler.py", line 2268, in create_backend
>     raise RuntimeError(
> Queue size: 0
> Extra options
> Running
> Pending
> Idle

</details>

After the error I tried to figure out how to install triton and found this to be an acceptable way of installing it in the comfyui portable location with python version 3.10.9:

> D:\VER_13\_AI\ComfyUI\python_embeded\python.exe -m pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl

Which seemed to work, but resulted in the next error:

<details>
  <summary>Error 2</summary>

> Error occurred when executing IF_WhisperSpeech:
> 
> partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)
> 
> 
> You can suppress this exception and fall back to eager by setting:
>     import torch._dynamo
>     torch._dynamo.config.suppress_errors = True
> 
> 
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_WishperSpeechNode\IFWhisperSpeechNode.py", line 114, in generate_audio
>     stoks = pipe.t2s.generate(chunk, cps=cps, show_progress_bar=False)[0]
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\whisperspeech\t2s_up_wds_mlang_enclm.py", line 462, in generate
>     toks[:,i+1] = self.generate_next(toks[:,i:i+1], toks_positions[i:i+1], cps_emb, xenc, xenc_positions, T, top_k)[:,0]
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\eval_frame.py", line 451, in _fn
>     return fn(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 921, in catch_errors
>     return callback(frame, cache_entry, hooks, frame_state, skip=1)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 400, in _convert_frame_assert
>     return _compile(
>   File "contextlib.py", line 79, in inner
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 703, in _compile
>     raise InternalTorchDynamoError(str(e)).with_traceback(
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 676, in _compile
>     guarded_code = compile_inner(code, one_graph, hooks, transform)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
>     r = func(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 535, in compile_inner
>     out_code = transform_code_object(code, transform)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1036, in transform_code_object
>     transformations(instructions, code_options)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 165, in _fn
>     return fn(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\convert_frame.py", line 482, in transform
>     tracer = InstructionTranslator(
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2085, in __init__
>     self._throw_if_in_functorch()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2126, in _throw_if_in_functorch
>     eager = torch._dynamo.lookup_backend("eager")
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\backends\registry.py", line 58, in lookup_backend
>     _lazy_import()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\backends\registry.py", line 91, in _lazy_import
>     import_submodule(backends)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\utils.py", line 1866, in import_submodule
>     importlib.import_module(f"{mod.__name__}.{filename[:-3]}")
>   File "importlib\__init__.py", line 126, in import_module
>   File "", line 1050, in _gcd_import
>   File "", line 1027, in _find_and_load
>   File "", line 1006, in _find_and_load_unlocked
>   File "", line 688, in _load_unlocked
>   File "", line 883, in exec_module
>   File "", line 241, in _call_with_frames_removed
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_dynamo\backends\cudagraphs.py", line 10, in 
>     from torch._inductor.cudagraph_trees import cudagraphify_impl
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\cudagraph_trees.py", line 71, in 
>     from torch._inductor.compile_fx import (
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\compile_fx.py", line 40, in 
>     from torch._inductor.codecache import code_hash, CompiledFxGraph, FxGraphCache
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\codecache.py", line 48, in 
>     from torch._inductor import config, exc, metrics
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\metrics.py", line 13, in 
>     from torch._inductor.utils import get_benchmark_name
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\torch\_inductor\utils.py", line 692, in 
>     from triton.compiler.compiler import AttrsDescriptor
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\triton\__init__.py", line 13, in 
>     from . import language
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\triton\language\__init__.py", line 2, in 
>     from . import core, extern, libdevice, random
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\triton\language\core.py", line 1141, in 
>     def abs(x):
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 386, in jit
>     return JITFunction(args[0], **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 315, in __init__
>     self.run = self._make_launcher()
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 282, in _make_launcher
>     scope = {"version_key": version_key(), "get_cuda_stream": get_cuda_stream,
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 82, in version_key
>     with open(triton._C.libtriton.__file__, "rb") as f:
> Queue size: 0
> Extra options
> Running
> Pending
> Idle
> 

</details>

Do you know how to fix that?
Thank you very much for your time!

**Comment by if-ai** [comment]
Hi, The torch compile for this only works if you have version torch v1.13 since we are using other things in comfy that require torch 2 it is not possible to activate the speed up is not that great anyway so it is better to deactivate torch compile. I will comeback to this at some point to improve it but for now is the best to deactivate torch compile. I am living with this issue myself.

**Comment by PrometheusDante** [comment]
Alright, I see. Thank you for the quick answer! It works just fine as is. Was just hoping for some amazing speed up, but if it's not that world-changing, I can do without it :)

I have another point, but I believe I should open a new post for that. It's about a small enhancement of naming the file save location, when outputting the sound. When specifying a folder within `output` it throws an error. I would appreciate outputting the files in a single folder with a simpler naming convention. Should I open an new post for that? I can also copy/paste the error it results in, if you want to look into that.

**Comment by if-ai** [comment]
I will try to get back at the other nodes when I finish the rag implementation in the main If AI tools I will add this and some other features is just that I don't know when I would be able to do it so I can't promise when but it seems easy to fix

**Comment by PrometheusDante** [comment]
Sounds great, thank you very much for your efforts!
